rows:
  - [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall]
  - [wall, flor, flor, flor, flor, flor, flor, flor, flor, wall]
  - [wall, flor, flor, flor, flor, flor, flor, flor, flor, wall]
  - [wall, flor, flor, flor, flor, flor, flor, flor, flor, wall]
  - [wall, flor, flor, flor, flor, flor, flor, flor, flor, wall]
  - [wall, flor, flor, flor, flor, flor, flor, flor, flor, wall]
  - [wall, flor, flor, flor, flor, flor, flor, flor, flor, wall]
  - [wall, flor, flor, flor, flor, flor, flor, flor, flor, wall]
  - [wall, flor, flor, flor, flor, flor, flor, flor, flor, wall]
  - [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall]
